const dark = {
  COLORS: {
    // CONTAINERS
    BODY_DEFAULT: "#000000",
    CONTAINER_DEFAULT: "#1C1C1C",
    CONTAINER_DEFAULT_HOVER: "#0F0F0F",

    // TEXTS
    TEXT_DEFAULT: "#E7E9EA",
    TEXT_DEFAULT_HOVER: "#E7E9EA",

    // INTERACTIONS
    ITEM_DEFAULT: "#6C4DE6",
    ITEM_DEFAULT_HOVER: "#6842ff",
  },
};

export default dark;
