const dark = {
  COLORS: {
    // CONTAINERS
    BODY_DEFAULT: "#000000",
    CONTAINER_DEFAULT: "#1C1C1C",
    CONTAINER_DEFAULT_HOVER: "#0F0F0F",

    // TEXTS
    TEXT_DEFAULT: "#D3D6D7",
    TEXT_DEFAULT_HOVER: "#E7E9EA",

    // INTERACTIONS
    ITEM_DEFAULT: "#4284E4",
    ITEM_DEFAULT_HOVER: "#6CB6FF",
  },
};

export default dark;
