const light = {
  COLORS: {
    // CONTAINERS
    BODY_DEFAULT: "#FFFFFF",
    CONTAINER_DEFAULT: "#C1C1C1",
    CONTAINER_DEFAULT_HOVER: "#DFDFDF",

    // TEXTS
    TEXT_DEFAULT: "#0D1117",
    TEXT_DEFAULT_HOVER: "#0D1117",

    // INTERACTIONS
    ITEM_DEFAULT: "#1A8CD8",
    ITEM_DEFAULT_HOVER: "#1f9cef",
  },
};

export default light;
