const light = {
  COLORS: {
    // CONTAINERS
    BODY_DEFAULT: "#FFFFFF",
    CONTAINER_DEFAULT: "#F5F5F5",
    CONTAINER_DEFAULT_HOVER: "#D1D1D1",

    // TEXTS
    TEXT_DEFAULT: "#0D1117",
    TEXT_DEFAULT_HOVER: "#0D1117",

    // INTERACTIONS
    ITEM_DEFAULT: "#0071fc",
    ITEM_DEFAULT_HOVER: "#1355FF",
  },
};

export default light;
